# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='product title')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('brand', models.CharField(max_length=200, verbose_name='product brand')),
                ('price', models.IntegerField(default=0, verbose_name='product price')),
                ('type', models.BooleanField(verbose_name='product type')),
            ],
        ),
    ]
