# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180711_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='DEFAULT VALUE', max_length=255, verbose_name='image url'),
        ),
    ]
